language: emacs-lisp
env:
  - EMACS=emacs24
  # - EMACS=emacs-snapshot

# We pass --verbose to all our Puppet commands to prevent Travis CI from being
# stuck because of lacking output.  We used to use --debug, but that is just too
# much information
before_install:
  # Bootstrap Puppet, and install our Puppet modules.
  - sudo apt-get update
  - sudo apt-get install puppet
  - sudo FACTER_travis=true puppet apply --verbose ./puppet/manifests/bootstrap.pp
  # Bootstrap test environment
  - sudo FACTER_travis=true puppet apply --verbose ./puppet/manifests/testenv.pp
install:
  # Install our packages
  - make EMACS=$EMACS deps
script:
  # Run unit tests.
  - make EMACS=$EMACS test
